### PR TITLE
add cmdline data and default spi device

### PR DESCRIPTION
**Pull request by timiskander**
Nice little tool...
I needed to send small amounts of commands to a spi device (register read/writes) so I added code to read byte values from the cmdline and send them.

### CODE REVIEW

**Comment by cpb-** [comment]
Sorry, I didn't see your pull-request yet.
Interesting idea. I'll take a look at your patch.

**Comment by timiskander** [comment]
No worries..
I fear my patch is a bit “sub-optimal” anyway. 

cheers
/Tim

**Comment by cpb-** [comment]
I had the same need to send some hex data bytes through SPI device and I considered applying your patch.
But I realized that using the `\x` prefix of the shell `printf` command I can do the same : 
`printf '\xAA\x00\x55' | spi-pipe...`
And this construction respects the "pipe" meaning of `spi-pipe`.

**Comment by timiskander** [comment]
That works! :)
thanks!

**Pull request closed without merging**
